### ISSUE TITLE
IntelliJ 2017.1 EAP exceptions

### ISSUE THREAD

**Issue by krasa** [felixtsu/idea-generate-fluent-interface#18]
```
Assertion failed: Member Chooser should be shown in a transaction, see AnAction#startInTransaction
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.ide.util.MemberChooser.show(MemberChooser.java:690)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$1.run(GenerateFluentInterfaceActionHandlerImpl.java:154)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:367)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

```
Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState:com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog5,1051,460,485x521,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Create Test,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]=true, ModalityState.NON_MODAL=true, ModalityState:com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog6,1059,498,442x404,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Generate equals() and hashCode(),defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]=true, ModalityState:Inspect Code... 1070296451: running=false; canceled=false=true, ModalityState.NON_MODAL=true, ModalityState:Resolving Reference... 559941006: running=false; canceled=false=true, ModalityState:com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog7,1034,434,1241x621,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Find in Path,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]=true, ModalityState:com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog8,1085,402,390x650,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Generate Fluent Interface Members,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]=false, ModalityState:com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog9,940,624,679x151,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Add File to Git,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]=true}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:244)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:75)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.treeChanged(PsiModificationTrackerImpl.java:97)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:362)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChildrenChange(PsiManagerImpl.java:260)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.sendBeforeChildrenChangeEvent(BlockSupportImpl.java:353)
	at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:378)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:151)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:646)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:753)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:81)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:530)
	at com.intellij.psi.impl.source.tree.java.ClassElement.addInternal(ClassElement.java:169)
	at com.intellij.psi.impl.source.JavaStubPsiElement.addAfter(JavaStubPsiElement.java:92)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.createMethodFromText(GenerateFluentInterfaceWorker.java:91)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.generateSetterMethods(GenerateFluentInterfaceWorker.java:68)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.execute(GenerateFluentInterfaceWorker.java:63)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$2$1.run(GenerateFluentInterfaceActionHandlerImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:999)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$2.run(GenerateFluentInterfaceActionHandlerImpl.java:199)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl.executeGenerateLater(GenerateFluentInterfaceActionHandlerImpl.java:197)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl.access$000(GenerateFluentInterfaceActionHandlerImpl.java:30)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$1.run(GenerateFluentInterfaceActionHandlerImpl.java:179)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:367)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by nrheckman** [comment]
Same behavior in 2017.3.2

`Assertion failed: Member Chooser should be shown in a transaction, see AnAction#startInTransaction
java.lang.Throwable: Assertion failed: Member Chooser should be shown in a transaction, see AnAction#startInTransaction
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:172)
	at com.intellij.ide.util.MemberChooser.show(MemberChooser.java:681)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$1.run(GenerateFluentInterfaceActionHandlerImpl.java:154)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`
`Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities:
    ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,1113,23,974x982,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Generate Fluent Interface Members,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]]}, writingAllowed=false;
    ModalityState.NON_MODAL, writingAllowed=true
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities:
    ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,1113,23,974x982,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Generate Fluent Interface Members,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]]}, writingAllowed=false;
    ModalityState.NON_MODAL, writingAllowed=true
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:232)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:93)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.incCountersInner(PsiModificationTrackerImpl.java:101)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.treeChanged(PsiModificationTrackerImpl.java:118)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:367)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChildrenChange(PsiManagerImpl.java:265)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.sendBeforeChildrenChangeEvent(BlockSupportImpl.java:353)
	at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:370)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:151)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:615)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:722)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:67)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:483)
	at com.intellij.psi.impl.source.tree.java.ClassElement.addInternal(ClassElement.java:169)
	at com.intellij.psi.impl.source.JavaStubPsiElement.addAfter(JavaStubPsiElement.java:92)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.createMethodFromText(GenerateFluentInterfaceWorker.java:91)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.generateGetterMethods(GenerateFluentInterfaceWorker.java:74)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.execute(GenerateFluentInterfaceWorker.java:60)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$2$1.run(GenerateFluentInterfaceActionHandlerImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$2.run(GenerateFluentInterfaceActionHandlerImpl.java:199)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl.executeGenerateLater(GenerateFluentInterfaceActionHandlerImpl.java:197)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl.access$000(GenerateFluentInterfaceActionHandlerImpl.java:30)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$1.run(GenerateFluentInterfaceActionHandlerImpl.java:179)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by okayliao** [comment]
2018.1.4

`Assertion failed: Member Chooser should be shown in a transaction, see AnAction#startInTransaction
java.lang.Throwable: Assertion failed: Member Chooser should be shown in a transaction, see AnAction#startInTransaction
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:163)
	at com.intellij.ide.util.MemberChooser.show(MemberChooser.java:681)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$1.run(GenerateFluentInterfaceActionHandlerImpl.java:154)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by amaury986** [comment]
2021.1

`java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:144)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:80)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.incCountersInner(PsiModificationTrackerImpl.java:86)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.treeChanged(PsiModificationTrackerImpl.java:96)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:338)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChildrenChange(PsiManagerImpl.java:231)
	at com.intellij.pom.core.impl.PomModelImpl.sendBeforeChildrenChangeEvent(PomModelImpl.java:350)
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:282)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:579)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:673)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:53)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:447)
	at com.intellij.psi.impl.source.tree.java.ClassElement.addInternal(ClassElement.java:169)
	at com.intellij.psi.impl.source.JavaStubPsiElement.addAfter(JavaStubPsiElement.java:72)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.createMethodFromText(GenerateFluentInterfaceWorker.java:91)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.generateSetterMethods(GenerateFluentInterfaceWorker.java:68)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceWorker.execute(GenerateFluentInterfaceWorker.java:63)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$2$1.run(GenerateFluentInterfaceActionHandlerImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$2.run(GenerateFluentInterfaceActionHandlerImpl.java:199)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl.executeGenerateLater(GenerateFluentInterfaceActionHandlerImpl.java:197)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl.access$000(GenerateFluentInterfaceActionHandlerImpl.java:30)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$1.run(GenerateFluentInterfaceActionHandlerImpl.java:179)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`
