### ISSUE TITLE
Assertion failed: Member Chooser should be shown in a transaction, see AnAction#startInTransaction

### ISSUE THREAD

**Issue by musjassani** [felixtsu/idea-generate-fluent-interface#21]
Assertion failed: Member Chooser should be shown in a transaction, see AnAction#startInTransaction
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.ide.util.MemberChooser.show(MemberChooser.java:690)
	at com.googlecode.generatefluentinterface.GenerateFluentInterfaceActionHandlerImpl$1.run(GenerateFluentInterfaceActionHandlerImpl.java:154)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mark--** [comment]
Seeing the same execpetion whenn generating a fluent setter for a class with a single field.
In the dialog the prefix is "with" and no checkbox is checked.
Plugin version is 0.8.5
